### PR TITLE
SB-103 - test data for the dev instance of School Bus

### PR DESCRIPTION
**Pull request by swcurran**
Basic test data for loading into the Dev instance of School Bus. Load scripts will be defined to load the data.

### CODE REVIEW

**Comment by swcurran** [comment]
Absolutely correct Robin - stupid of me.  We usually don't use siteminder in the dev instance, so it is less of a concern, but it is in this case.  Great catch. 

Removed - generated JSON file, generated CSV file and source of the CSV file in the Excel file with the user names.  We will not version control the users.  The rest of the data is randomly generated as you can see from the excel file.  All of the names that will be added to the file will be based on "Fake Data Generator" names that are in the "Names" tab of the Excel - fake names from a generator service - with all sorts of related fake data - address, email address, phone number, etc. etc.  Cool stuff.

Great catch - thanks!

FYI - once this pull request has gone through I will delete my github repo and recreate it from a fork of school bus.  That will eliminate the checkin that I did of this file and eliminate access to it from anywhere else.

**Comment by swcurran** [comment]
Other data - e.g. VIP Decals and so on are made up.

Excel Formula for VIP Decal: ="VIP-"&RANDBETWEEN(100000,500000)
Excel Formula for RegID = =RANDBETWEEN(10000000,50000000)

Some data is pulled from the original School Bus - Make, Model, Body, Fuel, Permit number and Independent school names. I don't think anyone would have a problem with those, but if so, I can make them up as well.

**Comment by robinwn** [comment]
thanks - can you confirm that the following are randomly generated and not randomly selected from a list of real data:
CCW_CCW.json
  ICBCCVIPDecal
  ICBCFleetUnitNo
  ICBCRegOwner<various>
  ICBCRegi
  etc

SchoolBus_SchoolBus.json
 VIN
 permitNumber
 plate
 regi

**Comment by robinwn** [comment]
a separate issue is concerning the use of SMUserID vs SMGUID.
User IDs can and do repeat over time whereas GUIDs are unique.
Permissions should use the GUID rather than the UserID.

**Comment by swcurran** [comment]
Rethought about the users and decided to leave them in but with fake names and no IDs. That allows us to just add the siteminder ID via the app, and we can re-assign users to test accounts as they come and go (clear the guid field, change the smuserId field.  Updated swagger.yaml file and added some more random data. Verified that all ID data on vehicles is random.

@robinwn - I think I've addressed your issues.  Please review and respond soon as we are trying to get testing data loaded.

See the user API and the JIRA about how we are handling auth with SMUserID and SMGUID.  Our approach is correct, I think, but that issue is unrelated to this PR.

Thanks

**Pull request merged**
